version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis:/data
    networks:
    - backend
  fcBackend:
    build: .
    networks:
    - backend
    image: feb18/fcbackend:0.0.2-SNAPSHOT
    ports:
    - 8000:8000
    stop_grace_period: 1m30s
    restart: 'no'
    links:
    - redis
    depends_on:
    - redis
volumes:
  redis: null
networks:
  backend: null