version: '3'
services:
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
    - 6379:6379
    volumes:
    - redis:/data
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgress
    - POSTGRES_DB=postgres
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - jenkinsnet
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    - SONAR_JDBC_PASSWORD=postgress
    - SONAR_JDBC_USERNAME=postgres
    ports:
    - 9000:9000
    - 9092:9092
    links:
    - postgres
    volumes:
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs
    - sonarqube_data:/opt/sonarqube/data
    networks:
    - jenkinsnet
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    restart: unless-stopped
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    ports:
    - 9080:8080
    links:
    - sonarqube    
    networks:
    - jenkinsnet    
    volumes:
    - jenkins-docker-certs:/certs/client
    - jenkins-data:/var/jenkins_home
networks:
  jenkinsnet: null
volumes:
  redis: null
  pgdata: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_data: null
  jenkins-docker-certs: null
  jenkins-data: null
